# Generated by Django 4.1.5 on 2023-01-24 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ElectricalProfilesSet",
            new_name="ElectricalProfileSet",
        ),
        migrations.AlterModelOptions(
            name="electricalprofileset",
            options={"verbose_name_plural": "Electrical profile sets"},
        ),
        migrations.AddField(
            model_name="timetable",
            name="electrical_profile_set",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="osrd_infra.electricalprofileset"
            ),
        ),
        migrations.AddField(
            model_name="trainschedulemodel",
            name="modes_and_profiles",
            field=models.JSONField(default=[]),
        ),
    ]
