# Generated by Django 4.1.2 on 2023-01-12 16:26

from django.db import migrations, models
import osrd_infra.schemas.external_generated_inputs
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0016_rollingstock_power_class"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electricalprofilesset",
            options={"verbose_name_plural": "Electrical profile sets"},
        ),
        migrations.AddField(
            model_name="electricalprofilesset",
            name="level_order",
            field=models.JSONField(
                default=dict,
                validators=[
                    osrd_infra.utils.PydanticValidator(
                        osrd_infra.schemas.external_generated_inputs.ElectricalProfileLevelOrder
                    )
                ],
            ),
        ),
    ]
