# Generated by Django 4.1.2 on 2023-01-18 18:21

from django.db import migrations, models
import django.db.models.deletion
import osrd_infra.schemas.external_generated_inputs
import osrd_infra.utils


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0017_remove_lpvpanellayer_obj_lpvpanellayer_obj_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electricalprofilesset",
            options={"verbose_name_plural": "Electrical profile sets"},
        ),
        migrations.AddField(
            model_name="electricalprofilesset",
            name="level_order",
            field=models.JSONField(
                default=dict,
                validators=[
                    osrd_infra.utils.PydanticValidator(
                        osrd_infra.schemas.external_generated_inputs.ElectricalProfileLevelOrder
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="electrical_profile_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="osrd_infra.electricalprofilesset",
            ),
        ),
        migrations.AddField(
            model_name="trainschedulemodel",
            name="modes_and_profiles",
            field=models.JSONField(default=[]),
        ),
    ]
