# Generated by Django 4.1.2 on 2023-01-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("osrd_infra", "0017_electricalprofilesset_add_level_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="electrical_profile_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="osrd_infra.electricalprofilesset",
            ),
        ),
    ]
